AWSTemplateFormatVersion: 2010-09-09
Description: >-
  arq-avzd-fin-be
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: True

Parameters:
  Project:
    Description: Project name
    Type: String
    Default: arq-avzd-fin-be
  Stage:
    Description: API Gateway stage
    Type: String
    Default: dev
  LambdaIAMRole:
    Description: Lambda IAM Role
    Type: String
    Default: arn:aws:iam::667648694495:role/eg-fin-lambda-role
  SecGroup:
    Description: Security Group
    Type: String
    Default: sg-01310086b54763de7
  SubnetId01:
    Description: Subnet Id 01
    Type: String
    Default: subnet-008719e0b115dd091
  SubnetId02:
    Description: Subnet Id 02
    Type: String
    Default: subnet-018f49f82bb1f263d

Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      ContentUri: layers/common/
      Description: Common layer for project
      LicenseInfo: MIT
      RetentionPolicy: Retain

  FinBeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:  !Transform
        Name: AWS::Include
        Parameters:
          Location: ./openapi.yaml
      Name: !Sub '${Project}-serverless-api'

  createPaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-create-payment'
      Handler: src/create-payment/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        CreatePaymentPost:
          Type: Api
          Properties:
            Path: /v1/payments
            Method: POST
            RestApiId: !Ref FinBeApi

  createPurchaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-create-purchase'
      Handler: src/create-purchase/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        CreatePurchasetPost:
          Type: Api
          Properties:
            Path: /v1/purchases
            Method: POST
            RestApiId: !Ref FinBeApi

  getFinancialStatementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-financial-statement'
      Handler: src/get-financial-statements/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/financial/statements
            Method: GET
            RestApiId: !Ref FinBeApi

  getCostCentersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-cost-centers'
      Handler: src/get-cost-centers/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/cost-centers
            Method: GET
            RestApiId: !Ref FinBeApi

  getCustomersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-customers'
      Handler: src/get-customers/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/customers
            Method: GET
            RestApiId: !Ref FinBeApi

  getInvoiceDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-invoice-details'
      Handler: src/get-invoice-details/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/invoices/{id}
            Method: GET
            RestApiId: !Ref FinBeApi

  getInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-invoices'
      Handler: src/get-invoices/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/invoices
            Method: GET
            RestApiId: !Ref FinBeApi

  getResponsiblesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-responsibles'
      Handler: src/get-responsibles/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/responsibles
            Method: GET
            RestApiId: !Ref FinBeApi

  getResposibleDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-responsible-details'
      Handler: src/get-responsible-details/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/responsibles/{id}
            Method: GET
            RestApiId: !Ref FinBeApi

  getResponsiblesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-responsibles'
      Handler: src/get-responsibles/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/responsibles
            Method: GET
            RestApiId: !Ref FinBeApi

  getProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-products'
      Handler: src/get-products/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/products
            Method: GET
            RestApiId: !Ref FinBeApi

  getProductDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Project}-${Stage}-get-product-details'
      Handler: src/get-product-details/index.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: PLEASE FILL ME!!!!!
      Role: !Ref LambdaIAMRole
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecGroup
        SubnetIds:
          - !Ref SubnetId01
          - !Ref SubnetId02
      Layers:
        - !Ref CommonLayer
      Events:
        FinancialStatementsPost:
          Type: Api
          Properties:
            Path: /v1/products/{id}
            Method: GET
            RestApiId: !Ref FinBeApi

Outputs:
  FinBeApiBaseUrl:
    Description: URL of created API
    Value: !Sub "https://${FinBeApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"